### ISSUE TITLE
Questions for P0~3 matrix in calib.txt

### ISSUE THREAD

**Issue by qsisi** [FoamoftheSea/KITTI_visual_odometry#1]
Hello! Thanks for creating this amazing repo along with the videos on Youtube for beginners of KITTI odometry datasets. Here I got a question about the projection matrix in calib.txt.

In my understanding, in the videos, you said the P0-3 matrices are the **rectified projection matrix**, which project 3D coordinates in the associated camera coordinate system (0-3) into the global reference frame (cam0, left grayscale camera). And you prove it by decomposing the projection matrix into the intrinsic and extrinsic matrix:
```
P1 = np.array(calib.loc['P1:']).reshape(3,4)
k1, r1, t1, _, _, _, _ = cv2.decomposeProjectionMatrix(P1)
t1 /= t1[3]
>>> print(k1)
[[718.856    0.     607.1928]
 [  0.     718.856  185.2157]
 [  0.       0.       1.    ]]
>>> print(r1)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
>>> print(t1) 
[[ 5.37165719e-001]
 [ 1.40649083e-017]
 [-4.94065646e-324]
 [ 1.00000000e+000]]
```
 Then, I tried to reverse the above operation:
```
Rt = np.hstack([r1, t1[:3]])
P = k1 @ Rt
>>>print(P.round(3))
[[718.856   0.    607.193 386.145]
 [  0.    718.856 185.216   0.   ]
 [  0.      0.      1.     -0.   ]]
>>>print(P1.round(3))
[[ 718.856    0.     607.193 -386.145]
 [   0.     718.856  185.216    0.   ]
 [   0.       0.       1.       0.   ]]
```
I found that the P is actually the negative of P1, it is because the function **cv2.decomposeProjectionMatrix** returns the **-t** instead of **t** for the translation vector. It is strange to me, could you kindly help me with this? Thanks.

Thank you so much for your help.

**Comment by FoamoftheSea** [comment]
Hi @qsisi - apologies for the late reply on this. Thank you for pointing this out, it appears that I was mistaken on this detail as well as meaning of the word rectified in this context when I wrote this, which led to your confusion. I will explain the mistake and fix it in the tutorial. 

The word "rectified" does not mean these projection matrices work in reverse, as I originally thought. It means that the rectification matrices have already been multiplied into them to account for image undistortion. According to the KITTI Odometry devkit README: 

> calib.txt: Calibration data for the cameras: P0/P1 are the 3x4 projection
matrices after rectification. Here P0 denotes the left and P1 denotes the
right camera. Tr transforms a point from velodyne coordinates into the
left rectified camera coordinate system. In order to map a point X from the
velodyne scanner to a point x in the i'th image plane, you thus have to
transform it like:
 x = Pi * Tr * X

This means that the Pi matrices actually do take points into their own coordinate frame. My confusion was caused by what you are seeing: if these matrices go from global -> cam, then why do the outputs of cv2.decomposeProjectionMatrix() seem to go in the other direction? The answer is that this function tells you the pose and rotation of the camera in the global coordinate frame, which in this case is indeed the left grayscale camera. So, while I got the final relationship right, I was wrong in saying that the projection matrices go in this direction. The cv2.decomposeProjectionMatrix() function reverses the direction of coordinate transform, which is clear from this excerpt from the [cv2 documentation](https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#gaaae5a7899faa1ffdf268cd9088940248):

> The function computes a decomposition of a projection matrix into a calibration and a rotation matrix and the position of a camera.

The last few words are the key: position of the CAMERA, meaning we must be talking about outputs in context of the global coordinate frame.

I hope that this is helpful, and again sorry for not noticing you had opened this issue sooner. I will fix the notebook, I appreciate you flagging this.
